package xdb.control;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Map;
import org.w3c.dom.Node;

/**
 * Interface for all renderers.
 * 
 * @author Paul Strack
 */
public interface Renderer {

    /**
     * Mime type generated by this renderer (text/html, text/xml, etc.).
     * 
     * @return The mime type.
     */
    public String getMimeType();

    /**
     * Write query results to an output stream.
     * 
     * @param results
     *            The list of results to render.
     * @param out
     *            The output stream.
     * @param params
     *            The query parameters.
     * @throws java.io.IOException
     *             For errors.
     */
    public void render(List<Node> results, PrintWriter out, Map<String, String[]> params)
        throws IOException;
}
